"""
Recompute every figure quoted in report/report.html, from one place.

The report is prose with numbers welded into it, and those numbers come from five
different scripts (train, ablation, seasonal_holdout, blend, report_figures) plus a few
that were never written down by any of them: Table 4's cross-season blend comparison, the
split-gain shares, the effective persistence weight over the submitted rows. When the
training table changes, the ones nobody owns are exactly the ones that go stale without
anything failing. So they get an owner here.

This writes data/processed/report_numbers.md and changes nothing else. In particular it
does NOT touch model_bundle/blend_weights.json: the spring weights it needs for Table 4
are fitted in memory and thrown away, because writing them would silently swap the
submitted configuration for the one the report uses as a foil.

Run last, after train.py -> blend.py --season autumn -> ablation.py ->
seasonal_holdout.py -> report_figures.py.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ablation import FEATURE_GROUPS, hurdle_predict
from blend import (AUTUMN_END, apply_blend, autumn_holdout, bucket_of, fit_weights,
                   reference_holdout)
from data_acquisition.eagle_i import PROCESSED_DIR
from model_bundle import load_bundle
from train import NON_FEATURE_COLS, VAL_START, load_table

TABLE_PATH = PROCESSED_DIR / "training_table_partial.parquet"
BUNDLE_DIR = PROCESSED_DIR / "model_bundle"
SUBMISSION_PATH = Path(__file__).resolve().parent.parent / "submission" / "predictions.csv"
OUT_PATH = PROCESSED_DIR / "report_numbers.md"
EVENT_THRESHOLD = 0.001


def rmse(pred: np.ndarray, truth: np.ndarray) -> float:
    return float(np.sqrt(((np.asarray(pred, dtype=float) - truth) ** 2).mean()))


def skill(pred: np.ndarray, truth: np.ndarray, reference: float) -> float:
    return 100.0 * (reference - rmse(pred, truth)) / reference


def season_block(val_df: pd.DataFrame, model_pred: np.ndarray,
                 weight_sets: dict[str, dict]) -> dict[str, tuple[float, float]]:
    """The five Table-4 predictors scored on one season's rows."""
    truth = val_df["target_x"].to_numpy()
    persistence = val_df["x_at_issue"].to_numpy()
    leads = val_df["lead_hours"].to_numpy()
    zero = rmse(np.zeros_like(truth), truth)

    # Persistence alone is undefined where EAGLE-I had no reading at issue time, so it is
    # scored only where it exists, against a zero baseline on those same rows.
    ok = ~np.isnan(persistence)
    out = {
        "always zero": (zero, 0.0),
        "persistence alone": (
            rmse(persistence[ok], truth[ok]),
            skill(persistence[ok], truth[ok], rmse(np.zeros(int(ok.sum())), truth[ok])),
        ),
        "model alone": (rmse(model_pred, truth), skill(model_pred, truth, zero)),
    }
    for label, weights in weight_sets.items():
        blended = apply_blend(model_pred, persistence, leads, weights)
        out[label] = (rmse(blended, truth), skill(blended, truth, zero))
    return out


def gain_shares(feature_names: list[str], gains: np.ndarray) -> tuple[pd.DataFrame, dict[str, float]]:
    total = gains.sum()
    per_feature = (pd.DataFrame({"feature": feature_names, "share": 100.0 * gains / total})
                   .sort_values("share", ascending=False).reset_index(drop=True))
    by_group = {group: float(per_feature.loc[per_feature.feature.isin(cols), "share"].sum())
                for group, cols in FEATURE_GROUPS.items()}
    return per_feature, by_group


def main() -> None:
    df = load_table(TABLE_PATH)
    lines: list[str] = [
        "# Numbers quoted in report/report.html",
        "",
        "Regenerated by `code/report_numbers.py`. Section numbers are the report's.",
    ]

    def section(title: str) -> None:
        lines.extend(["", f"## {title}", ""])

    def item(text: str) -> None:
        lines.append(f"- {text}")

    # --- corpus -------------------------------------------------------------------
    section("Corpus (sections 1, 5, 6, 8)")
    train_df = df[df["issue_time"] < VAL_START]
    val_df_ref = df[df["issue_time"] >= VAL_START]
    x = df["target_x"]
    item(f"forecast runs in the table: **{df['issue_time'].nunique()}**")
    item(f"rows: **{len(df):,}** ({len(df) / 1e6:.2f} million), "
         f"span {df['issue_time'].min().date()} .. {df['issue_time'].max().date()}")
    item(f"counties: **{df['fips_code'].nunique()}**")
    item(f"training rows (before {VAL_START.date()}): **{len(train_df):,}** "
         f"({len(train_df) / 1e6:.2f} million, {100 * len(train_df) / len(df):.1f}%)")
    item(f"validation rows: **{len(val_df_ref):,}** ({100 * len(val_df_ref) / len(df):.1f}%), of which "
         f"**{int((val_df_ref['target_x'] > EVENT_THRESHOLD).sum()):,}** have x > {EVENT_THRESHOLD} and "
         f"**{int((val_df_ref['target_x'] <= EVENT_THRESHOLD).sum()):,}** do not")
    item(f"target exactly zero: **{100 * (x == 0).mean():.1f}%** of all rows "
         f"(nonzero {100 * (x > 0).mean():.1f}%, above {EVENT_THRESHOLD}: "
         f"{100 * (x > EVENT_THRESHOLD).mean():.1f}%)")
    item(f"mean x: **{x.mean():.5f}**")
    item(f"positive rows: validation **{100 * (val_df_ref['target_x'] > 0).mean():.1f}%** "
         f"vs training **{100 * (train_df['target_x'] > 0).mean():.1f}%**")
    item(f"validation rows with x exactly zero: **{int((val_df_ref['target_x'] == 0).sum()):,}**")
    counties = pd.read_csv(PROCESSED_DIR / "training_counties.csv", dtype={"fips_code": str})
    item(f"training counties span **{counties['state'].nunique()}** states")

    # Run cadence is no longer uniform: the autumn block was densified to daily, the rest
    # was not, and section 3.3 of the report describes the cadence.
    runs = pd.Series(sorted(df["issue_time"].unique()))
    for label, lo, hi in [("Sep-Dec 2024", "2024-09-01", "2025-01-01"),
                          ("Jan-Aug 2025", "2025-01-01", "2025-09-01")]:
        block = runs[(runs >= pd.Timestamp(lo)) & (runs < pd.Timestamp(hi))]
        days = block.dt.normalize().nunique()
        span_days = (min(pd.Timestamp(hi), runs.max() + pd.Timedelta(days=1))
                     - pd.Timestamp(lo)).days
        item(f"cadence {label}: **{len(block)} runs** on {days} distinct days out of "
             f"{span_days} ({len(block) / max(days, 1):.1f} runs/day covered, "
             f"one day in {span_days / max(days, 1):.1f} covered)")

    # --- split gain ---------------------------------------------------------------
    section("Split gain (section 1, Table 3, section 7)")
    bundle = load_bundle(BUNDLE_DIR)
    gains = np.asarray(bundle.booster.feature_importance(importance_type="gain"), dtype=float)
    per_feature, by_group = gain_shares(list(bundle.booster.feature_name()), gains)
    group_of = {c: g for g, cols in FEATURE_GROUPS.items() for c in cols}
    lines.extend(["", "| Feature | Gain share | Group |", "|---|---|---|"])
    for _, r in per_feature.head(7).iterrows():
        lines.append(f"| `{r.feature}` | {r.share:.1f} % | {group_of.get(r.feature, '?')} |")
    lines.append("")
    weather = by_group["weather_raw"] + by_group["weather_derived"] + by_group["climatology"]
    for group, share in sorted(by_group.items(), key=lambda kv: -kv[1]):
        item(f"group `{group}`: **{share:.0f} %** of total split gain")
    item(f"all weather together (raw + derived + climatology): **{weather:.0f} %**")

    # --- Table 2 ------------------------------------------------------------------
    section("Table 2 - reference split (from ablation_results.csv)")
    # Rendered by hand rather than DataFrame.to_markdown, which needs `tabulate` —
    # an extra dependency the clean-clone reproduction would have to install.
    abl = pd.read_csv(PROCESSED_DIR / "ablation_results.csv")
    lines.extend(["", "| " + " | ".join(abl.columns) + " |",
                  "|" + "---|" * len(abl.columns)])
    for _, r in abl.iterrows():
        cells = [f"{v:.6f}" if isinstance(v, float) else str(v) for v in r]
        lines.append("| " + " | ".join(cells) + " |")

    # --- Table 4 ------------------------------------------------------------------
    section("Table 4 - the same predictors in two seasons")
    shipped = json.loads((BUNDLE_DIR / "blend_weights.json").read_text("utf8"))
    autumn_val, autumn_pred, autumn_label = autumn_holdout(df)
    refit_autumn = fit_weights(autumn_val, autumn_pred, quiet=True)
    if refit_autumn != shipped:
        item("**WARNING** - refitting the autumn weights here did not reproduce "
             "`blend_weights.json`; the shipped weights are stale. Re-run "
             "`blend.py --season autumn`.")
        item(f"shipped: `{json.dumps(shipped)}`")
        item(f"refit:   `{json.dumps(refit_autumn)}`")
    ref_val, ref_pred, ref_label = reference_holdout(df)
    spring = fit_weights(ref_val, ref_pred, quiet=True)  # in memory only, never written

    weight_sets = {"blend, spring-fitted weights": spring,
                   "blend, autumn-fitted weights (submitted)": shipped}
    autumn = season_block(autumn_val, autumn_pred, weight_sets)
    reference = season_block(ref_val, ref_pred, weight_sets)
    item(f"autumn column: {autumn_label}")
    item(f"reference column: {ref_label}")
    ok_autumn = int((~np.isnan(autumn_val["x_at_issue"].to_numpy())).sum())
    ok_ref = int((~np.isnan(ref_val["x_at_issue"].to_numpy())).sum())
    item(f"persistence is defined on {ok_autumn:,}/{len(autumn_val):,} autumn rows and "
         f"{ok_ref:,}/{len(ref_val):,} reference rows")
    lines.extend(["", "| Predictor | Autumn RMSE | skill | Reference RMSE | skill |",
                  "|---|---|---|---|---|"])
    for key, (a, a_skill) in autumn.items():
        r, r_skill = reference[key]
        a_cell = "-" if key == "always zero" else f"{a_skill:+.1f} %"
        r_cell = "-" if key == "always zero" else f"{r_skill:+.1f} %"
        lines.append(f"| {key} | {a:.6f} | {a_cell} | {r:.6f} | {r_cell} |")
    lines.append("")
    item("weights, spring fit: " + " / ".join(f"{v['w_persistence']:.2f}" for v in spring.values()))
    item("weights, autumn fit (shipped): "
         + " / ".join(f"{v['w_persistence']:.2f}" for v in shipped.values()))
    item("half-lives, autumn fit: " + " / ".join(
        "flat" if v["halflife_h"] is None else f"{v['halflife_h']}h" for v in shipped.values()))

    # --- what the restoration decay buys (section 5.1) ------------------------------
    section("Restoration decay against flat carry-forward (section 5.1)")
    flat_only = fit_weights(autumn_val, autumn_pred, quiet=True, halflives=[None])
    truth_autumn = autumn_val["target_x"].to_numpy()
    pers_autumn = autumn_val["x_at_issue"].to_numpy()
    leads_autumn = autumn_val["lead_hours"].to_numpy()
    flat_rmse = rmse(apply_blend(autumn_pred, pers_autumn, leads_autumn, flat_only), truth_autumn)
    decayed_rmse = autumn["blend, autumn-fitted weights (submitted)"][0]
    chosen = [b for b, v in shipped.items() if v["halflife_h"] is not None]
    item(f"the fit picks a decay in **{len(chosen)} of {len(shipped)}** buckets "
         f"({', '.join(chosen)}); flat elsewhere")
    item(f"blended autumn RMSE: flat-only fit {flat_rmse:.6f} -> decay allowed "
         f"{decayed_rmse:.6f} = **{100 * (flat_rmse - decayed_rmse) / flat_rmse:.2f} %** overall")
    item("weights under a flat-only fit: "
         + " / ".join(f"{v['w_persistence']:.2f}" for v in flat_only.values()))

    # --- the hurdle alternative (section 7.2) ---------------------------------------
    section("The hurdle alternative in the autumn window (section 7.2)")
    autumn_train = df[df["issue_time"] >= AUTUMN_END]
    feature_cols = [c for c in df.columns if c not in NON_FEATURE_COLS]
    heads = {"delta": autumn_pred}
    for tau in (0.0, EVENT_THRESHOLD):
        heads[f"hurdle (tau={tau:g})"] = hurdle_predict(
            autumn_train, autumn_val, feature_cols, threshold=tau)
    blended_rmse = {}
    for label, pred in heads.items():
        # Each head gets its own weights: comparing them under weights fitted for the
        # delta head would score the other two on a blend nobody would ship.
        own = shipped if label == "delta" else fit_weights(autumn_val, pred, quiet=True)
        blended_rmse[label] = rmse(apply_blend(pred, pers_autumn, leads_autumn, own), truth_autumn)
        item(f"`{label}`: standalone autumn RMSE **{rmse(pred, truth_autumn):.6f}**, "
             f"blended under its own weights **{blended_rmse[label]:.6f}**")
    spread = max(blended_rmse.values()) - min(blended_rmse.values())
    item(f"spread across the three blended heads: **{spread:.6f}** = "
         f"**{100 * spread / min(blended_rmse.values()):.2f} %**")

    # --- Figure 1 -----------------------------------------------------------------
    section("Figure 1 - skill by lead bucket, autumn window")
    curve = pd.read_csv(PROCESSED_DIR / "report_skill_by_lead_autumn.csv")
    zero_by_bucket = curve[curve.model == "always zero"].set_index("bucket")["rmse"]
    item(f"rows plotted: **{int(curve[curve.model == 'always zero']['n'].sum()):,}**")
    lines.extend(["", "| Bucket | persistence | model | blended |", "|---|---|---|---|"])
    for b in zero_by_bucket.index:
        cells = []
        for m in ["persistence", "model", "blended"]:
            v = float(curve[(curve.model == m) & (curve.bucket == b)]["rmse"].iloc[0])
            cells.append(f"{100 * (zero_by_bucket[b] - v) / zero_by_bucket[b]:+.0f} %")
        lines.append(f"| {b} | " + " | ".join(cells) + " |")

    # --- submitted file -----------------------------------------------------------
    section("The submitted file (sections 1, 8)")
    sub = pd.read_csv(SUBMISSION_PATH, dtype={"fips_code": str},
                      parse_dates=["issue_time", "target_time"])
    lead = (sub["target_time"] - sub["issue_time"]).dt.total_seconds() / 3600.0
    buckets = bucket_of(lead).astype(str).to_numpy()
    effective = np.zeros(len(sub))
    for b, spec in shipped.items():
        sel = buckets == b
        halflife = spec.get("halflife_h")
        decay_factor = 1.0 if halflife is None else np.power(0.5, lead[sel] / float(halflife))
        effective[sel] = spec["w_persistence"] * decay_factor
    item(f"rows: **{len(sub):,}** (Task A {int((sub.task_id == 'A').sum()):,}, "
         f"Task B {int((sub.task_id == 'B').sum()):,} = {100 * (sub.task_id == 'B').mean():.0f} % "
         f"of the file)")
    item(f"Task A issue times: **{sub[sub.task_id == 'A'].issue_time.nunique()}**, "
         f"Task B issue times: **{sub[sub.task_id == 'B'].issue_time.nunique()}**, "
         f"counties: **{sub.fips_code.nunique()}**")
    # Only the buckets the submission actually reaches: Task A stops at 48 h, so the
    # (48, 72] bucket is empty here and averaging over it would report a nan.
    occupied = [b for b in shipped if (buckets == b).any()]
    item(f"effective persistence weight actually applied: **{effective.mean():.2f}** averaged over "
         f"the submitted rows (shortest bucket {occupied[0]} **"
         f"{effective[buckets == occupied[0]].mean():.2f}**, longest reached {occupied[-1]} **"
         f"{effective[buckets == occupied[-1]].mean():.2f}**; buckets "
         f"{[b for b in shipped if b not in occupied]} are never reached)")

    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf8")
    print("\n".join(lines))
    print(f"\nWrote {OUT_PATH}")


if __name__ == "__main__":
    main()
